title: Huzefa's Personal Website
author: Huzefa Tapya
email: huzefa.tapya@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal website which displays my achievements and hobbies
  as well as other information about me.
theme: minima
# social links
snapchat_username: htapya11
github_username:  htapya11
discord_username: huzefa#4554

show_excerpts: true # set to false to remove excerpts on the homepage
