title: Huzefa's Personal Website
author: Huzefa Tapya
email: huzefa.tapya@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal website which displays my achievements and hobbies
  as well as other information about me.
theme: minima
# social links
github_username:  htapya11
facebook_username: huzefa.tapya@gmail.com

show_excerpts: true # set to false to remove excerpts on the homepage
